server:
  port: 8888
kafka:
  producer:
    productTopic: products
    bootstrapAddress: localhost:9092
    maxRequestSizeConfig: 20971520


hibernate:
  ddl-auto: create-drop
spring:
  datasource:
    url: jdbc:h2:mem:./demo-shop-with-spring
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console
  output:
    ansi:
      enabled: ALWAYS
